# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Julien Moeys
tagline:             '&middot Soil scientist &middot R programmer &middot Data analyst'
description:         'Julien Moeys homepage'
url:                 http://julienmoeys.info/
baseurl:             /
paginate:            5
encoding:            utf-8

# Github source code
github:              https://github.com/julienmoeys/julienmoeys.github.io

# About/contact
author:
  name:              Julien Moeys
  url:               http://julienmoeys.info/
  email:             contact@julienmoeys.info

# Custom vars
version:             1.0.0

# Excluded files
exclude:
    - ITLabBook.md
    - TODOLIST.md
    - INSPIRATION.md
    - README.md 
    - LICENSE.md
    - "*.md0"
    - "*.R"
    - "*.Rout"
    - "*.Rmd"
    - "*.bat"
    - "*.RData"
    - "*.BIB.bak"
    - docs/

