
rm( list = ls( all = TRUE ) ) 

# GENERAL OPTIONS
if( Sys.info()[[ "sysname" ]] == "Linux" ){ 
    setwd( wd <- "/home/jules/Documents/julienmoeys.info/julienmoeys.github.io" )
}else{ 
    setwd( wd <- "D:/Users/julienm/Documents/_WORKS/_WEB/julienmoeys.github.io" )
}   

inFile   <- "Publications.md0"
outFile  <- "Publications.md" 
bibFiles <- sprintf( "assets/bib/%s", c( "MOEYS_J_PUB_PEER.BIB", 
    "MOEYS_J_PUB_THESIS.BIB" ) ) 
me       <- "Moeys"


# Reference list ================================================

library( "tools" )

if( !require("bibtex") ){ 
    install.packages( "bibtex" ) 
    library( "bibtex" )
    #   help( pack = "bibtext" ) 
}   

#   Import the template md file
md <- readLines( con = inFile, encoding = "UTF-8-BOM" ) # Was encoded explicitely in UTF-8 without BOM

#   Import the bib files
bibData <- lapply( 
    X   = bibFiles, 
    FUN = function(bf){ 
        # bf <- bibFiles[ 1L ]
        
        out <- read.bib( file = bf, encoding = "UTF-8" ) 
        
        #   Find and sort by the publication year
        yr <- unlist( lapply( unclass( out ), function(b){ b[[ "year" ]] } ) )
        out <- out[ order( yr, decreasing = TRUE ) ]
        
        #   Extract publication url and doi
        url <- unlist( lapply( unclass( out ), function(b){ 
            if( is.null( b[[ "url" ]] ) ){ 
                return( NA_character_ ) 
            }else{ 
                return( b[[ "url" ]] ) 
            }   
        } ) ) 
        
        doi <- unlist( lapply( unclass( out ), function(b){ 
            if( is.null( b[[ "doi" ]] ) ){ 
                return( NA_character_ ) 
            }else{ 
                return( sprintf( "http://dx.doi.org/%s", b[[ "doi" ]] ) ) 
            }   
        } ) )
        
        out <- format( x = out, "text" ) 
        
        out <- sprintf( "%s. %s", 1:length(out), out )
        
        # Substitute line ending by spaces
        out <- unlist( lapply( 
            X   = out, 
            FUN = function(txt){ 
                return( gsub( x = txt, pattern = "\n", 
                    replacement = " ", fixed = FALSE ) )
            }   
        ) ) 
        
        # Put name in bold
        out <- unlist( lapply( 
            X   = out, 
            FUN = function(txt){ 
                return( gsub( x = txt, pattern = me, 
                    replacement = sprintf( "**%s**", me ), 
                    fixed = FALSE ) )
            }   
        ) ) 
        
        # Remove <URL: > statement, and replace url and doi by html version
        out <- unlist( lapply( 
            X   = 1:length(out), 
            FUN = function( i ){
                txt <- out[ i ]
                 
                txt <- gsub( x = txt, pattern = "<URL: ", 
                    replacement = "", fixed = FALSE )
                
                txt <- gsub( x = txt, pattern = ">", 
                    replacement = " ", fixed = FALSE )
                
                if( !is.na( doi[ i ] ) ){ 
                    txt <- gsub( x = txt, pattern = doi[ i ], 
                        replacement = sprintf( "<a href=\"%s\">DOI</a>", doi[ i ] ), 
                        fixed = FALSE )
                }   
                
                if( ( !is.na( url[ i ] ) ) & ( !identical( url[ i ], doi[ i ] ) ) ){
                    txt <- gsub( x = txt, pattern = url[ i ], 
                        replacement = sprintf( "<a href=\"%s\">URL</a>", url[ i ] ), 
                        fixed = FALSE )
                }   
                
                return( txt )
            }   
        ) ) 
        
        return( out )
    }   
)   


# Add a do not edit warning to the .md version of the file
rowNb0 <- grep( 
    x       = md, 
    pattern = "INSERT WARNING", 
    fixed   = TRUE ) 

md <- c( 
    md[ (1:length(md)) < rowNb0 ], 
    "<!-- DO NOT EDIT THIS FILE. EDIT Publications.md0 INSTEAD -->", 
    md[ (1:length(md)) > rowNb0 ] ) 


for( iBib in 1:length(bibFiles) ){ 
    # iBib <- 1
    
    rowNb <- grep( 
        x       = md, 
        pattern = sprintf( "INSERT %s", bibFiles[ iBib ] ), 
        fixed   = TRUE ) 
    
    if( length(rowNb) > 0 ){ 
        md <- c( 
            md[ (1:length(md)) < rowNb ], 
            bibData[[ iBib ]], 
            md[ (1:length(md)) > rowNb ] ) 
    }else{ 
        warning( "No tag found for the bibliography" )
    }   
}   

# showNonASCII( x = md )
# # Should show nothing!

f <- file( description = outFile, open = "wt", encoding = "UTF-8" ) 
writeLines( text = md, con = f )
# write( x = md, file = f )
# cat( paste( md, collapse="\n" ), "\n", sep = "", file = f )
close( f )


